FIND_PATH(GLOG_INCLUDE_DIR NAMES glog/logging.h)
FIND_LIBRARY(GLOG_LIBRARY glog)

INCLUDE(FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(Glog DEFAULT_MSG GLOG_LIBRARY GLOG_INCLUDE_DIR)

mark_as_advanced(GLOG_LIBRARY GLOG_INCLUDE_DIR)
